const languages = [
    { label: '', value: ''},  
    { label: 'Alemão', value: 'de'},  
    { label: 'Árabe', value: 'ar'},  
    { label: 'Bengali', value: 'bn'},  
    { label: 'Chinês', value: 'zh'},  
    { label: 'Coreano', value: 'ko'},  
    { label: 'Dinamarquês', value: 'da'},  
    { label: 'Eslovaco', value: 'sk'},  
    { label: 'Esloveno', value: 'sl'},  
    { label: 'Espanhol', value: 'es'},  
    { label: 'Finlandês', value: 'fi'},  
    { label: 'Francês', value: 'fr'},  
    { label: 'Grego', value: 'el'},  
    { label: 'Holandês', value: 'nl'},  
    { label: 'Húngaro', value: 'hu'},  
    { label: 'Indiano', value: 'hi'},  
    { label: 'Indonésio', value: 'id'},  
    { label: 'Inglês', value: 'en'},  
    { label: 'Italiano', value: 'it'},  
    { label: 'Japonês', value: 'ja'},  
    { label: 'Norueguês', value: 'no'},  
    { label: 'Polonês', value: 'pl'},  
    { label: 'Português', value: 'pt'},  
    { label: 'Romeno', value: 'ro'},  
    { label: 'Russo', value: 'ru'},  
    { label: 'Sérvio', value: 'sr'},  
    { label: 'Sueco', value: 'sv'},  
    { label: 'Tailandês', value: 'th'},  
    { label: 'Tcheco', value: 'cs'},  
    { label: 'Turco', value: 'tr'},  
]
export default languages